### ISSUE TITLE
Twitter preview op Slack mist

### ISSUE THREAD

**Issue by timoerlemans** [saberone/codeklets-main-site#14]
Als ik een Twitterlink op Slack deelt, wordt hier geen voorvertoning aan toegevoegd. Zou dit toegevoegd kunnen worden?

**Comment by saberone** [comment]
Het is besproken. De vraag is in behandeling genomen. En ik kan mededelen dat de voorvertoning van Tweets nu aanstaat in de CodeKlets Slack.
